name: ci

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.8", "3.9"]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install poetry
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          sudo apt-get install libsndfile1        
          python -m pip install poetry

      - name: Install dependencies
        run: |
          sudo apt-get install libsndfile1        
          python -m poetry install

      - name: Run unit tests
        run: |
          make tests
